import img2 from '../assets/images/Rectangle 22.png';

export const teacherData = [
    {
        teacherName: 'Abdujalilov Hasan Abduazizovich',
        position: 'Frontend dasturchi',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, nulla ea? Deserunt voluptates nam vel quas veniam fuga minus quo! Ea, sequi.',
        teacherImg: '',
        cardImg: img2,
    },
    {
        teacherName: 'Abdujalilov Hasan Abduazizovich',
        position: 'Frontend dasturchi',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, nulla ea? Deserunt voluptates nam vel quas veniam fuga minus quo! Ea, sequi.',
        teacherImg: '',
        cardImg: img2,
    },
    {
        teacherName: 'Abdujalilov Hasan Abduazizovich',
        position: 'Frontend dasturchi',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, nulla ea? Deserunt voluptates nam vel quas veniam fuga minus quo! Ea, sequi.',
        teacherImg: '',
        cardImg: img2,
    },
    {
        teacherName: 'Abdujalilov Hasan Abduazizovich',
        position: 'Frontend dasturchi',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, nulla ea? Deserunt voluptates nam vel quas veniam fuga minus quo! Ea, sequi.',
        teacherImg: '',
        cardImg: img2,
    },
    {
        teacherName: 'Abdujalilov Hasan Abduazizovich',
        position: 'Frontend dasturchi',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, nulla ea? Deserunt voluptates nam vel quas veniam fuga minus quo! Ea, sequi.',
        teacherImg: '',
        cardImg: img2,
    },
    {
        teacherName: 'Abdujalilov Hasan Abduazizovich',
        position: 'Frontend dasturchi',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, nulla ea? Deserunt voluptates nam vel quas veniam fuga minus quo! Ea, sequi.',
        teacherImg: '',
        cardImg: img2,
    },
    {
        teacherName: 'Abdujalilov Hasan Abduazizovich',
        position: 'Frontend dasturchi',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, nulla ea? Deserunt voluptates nam vel quas veniam fuga minus quo! Ea, sequi.',
        teacherImg: '',
        cardImg: img2,
    },
    {
        teacherName: 'Abdujalilov Hasan Abduazizovich',
        position: 'Frontend dasturchi',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, nulla ea? Deserunt voluptates nam vel quas veniam fuga minus quo! Ea, sequi.',
        teacherImg: '',
        cardImg: img2,
    },
    {
        teacherName: 'Abdujalilov Hasan Abduazizovich',
        position: 'Frontend dasturchi',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, nulla ea? Deserunt voluptates nam vel quas veniam fuga minus quo! Ea, sequi.',
        teacherImg: '',
        cardImg: img2,
    },
    {
        teacherName: 'Abdujalilov Hasan Abduazizovich',
        position: 'Frontend dasturchi',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, nulla ea? Deserunt voluptates nam vel quas veniam fuga minus quo! Ea, sequi.',
        teacherImg: '',
        cardImg: img2,
    },
    {
        teacherName: 'Abdujalilov Hasan Abduazizovich',
        position: 'Frontend dasturchi',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, nulla ea? Deserunt voluptates nam vel quas veniam fuga minus quo! Ea, sequi.',
        teacherImg: '',
        cardImg: img2,
    },
    {
        teacherName: 'Abdujalilov Hasan Abduazizovich',
        position: 'Frontend dasturchi',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, nulla ea? Deserunt voluptates nam vel quas veniam fuga minus quo! Ea, sequi.',
        teacherImg: '',
        cardImg: img2,
    },
];
